In [2]:
#NUMPY-Numerical python
#multidimensional array
import numpy as np
arr=[i for i in range(0,100)]
np_arr=np.arange(100)
print(arr)
print(np_arr)
#size of one element in numpy array
print(np_arr.itemsize)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
8


In [4]:
arr=[1,2,3,4]
np_arr=np.array(arr)
print(np_arr+1)

[2 3 4 5]


In [ ]:
#if we have import some csv file and have research on it


In [ ]:
#three dimensional array
import numpy as np
C=np.array([[[1,2,3],[4,5,6],[0,0, -1]],[[-1,-2,-3],[-4,-5,-6],[0,0,1]]])

In [ ]:
C[1,0,2]

-3

In [ ]:
C.shape #it returns a tuple

(2, 3, 3)

In [ ]:
#C.shape[0]-how many 2d arrays rows
#C.shape[1]-how many elements  columns
#C.shape[2]-in 1d array how many elements are there 



2

In [ ]:
#A=np.array([2])
#ndim-1
#b=np.array(3)
#ndim-0

In [ ]:
#size of 100elements in numpy array
print(np_arr.itemsize*np_arr.size)

800


In [ ]:
import sys
a=20
print(sys.getsizeof(a))
print(sys.getsizeof(1)*len(arr))

28
2800


In [ ]:
import time
import numpy as np
size = 100000

def addition_using_list():
    t1 = time.time()
    a = range(size)
    b = range(size)
    c = [a[i] + b[i] for i in range(size)]
    t2 = time.time()
    return (t2-t1)
def addition_using_numpy():
    t1 = time.time()
    a =np.arange(size)
    b =np.arange(size)
    c =a+b
    t2 = time.time()
    return (t2-t1)
t_list=addition_using_list()
t_numpy=addition_using_numpy()
print("list=",t_list*1000)
print("numpy=",t_numpy*1000)



list= 42.723894119262695
numpy= 1.6927719116210938


In [ ]:
#numpy is easier to calculate in less time.
#because it is written in c and fortran language
#creating
import numpy as np
a=[1,2,3]
b=np.array(a)
print(b)
print(type(b))



[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a.ndim)

2


In [ ]:
# a=[1,2,3,"a",4.5]
a=[1,2,3,3.5,4.5]
b=np.array(a,dtype='int')
print(b)

[1 2 3 3 4]


In [ ]:
a[0,2]

3

In [ ]:
a=[1,2,3,3.5,4.5]
b=np.array(a*3)
print(b)

[1.  2.  3.  3.5 4.5 1.  2.  3.  3.5 4.5 1.  2.  3.  3.5 4.5]


In [ ]:
B=np.array([[1,2,3,-1],[2,4,5,9]])

In [ ]:
B.ndim

2

In [ ]:
B[0,2] #used to print 2nd index of array 1

3

In [ ]:
# LETS START WITH PLACE HOLDER OF ARRAYS

In [ ]:
b=np.ones(3)
b

array([1., 1., 1.])

In [ ]:
b=np.zeros(3,dtype=int)
print(b)

[0 0 0]


In [ ]:
b=np.zeros((3,4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
b=np.full(3,5)
b

array([5, 5, 5])

In [ ]:
b=np.empty([3, 3])
b

array([[5.05206897e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [ ]:
b=np.zeros(10)
b[4]=1
b

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [ ]:
#numpy different function
import numpy as np
b=np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#numpy different function
import numpy as np
b=np.arange(2,10)
b

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
import numpy as np
b=np.arange(2,10,2)
b

array([2, 4, 6, 8])

In [ ]:
#linspace function
b=np.linspace(2,10)
b
#difference
d=b[1]-b[0]
d

0.16326530612244916

In [ ]:
b=np.linspace(2,10,5,dtype='int')
b

array([ 2,  4,  6,  8, 10])

In [ ]:
b=np.linspace(2,10,5,dtype='int',endpoint=False)
b
#in this 10 will not be included


array([2, 3, 5, 6, 8])

In [ ]:
b=np.identity(3)
#we can use np.identity as np.eye
b
#it will create identity matrix whose diagonal elements are 1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#it will generate number between 0-1
b=np.random.rand(3)
b


array([0.85655996, 0.88774117, 0.47333128])

In [ ]:
#it will generate 2d matrix
b=np.random.rand(2,3)
b


array([[0.48445646, 0.11823159, 0.54968197],
       [0.50065405, 0.7807988 , 0.54027136]])

In [ ]:
#to generate 0-10
b=np.random.rand(10)*10
b

array([1.60574578, 8.26543989, 1.78802586, 6.7190784 , 5.63597259,
       5.05591967, 4.37164588, 3.07835844, 5.67673841, 9.18840384])

In [ ]:
a=np.array([0,1,2,3])
a.shape
#it will return tuple defining its rows and cols

(4,)

In [ ]:
b=np.random.randint(10,4)
b.size

NameError: name 'np' is not defined

In [ ]:
b=np.random.randint(10,size=(4,4))
b

array([[7, 9, 1, 4],
       [5, 1, 3, 3],
       [1, 9, 6, 2],
       [4, 1, 9, 9]])

In [ ]:
import numpy as np

# Create the array using arange
my_array = np.arange(9, 50)

# Display the array
print(my_array)

[ 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32
 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
import numpy as np

# Create an identity-like matrix of size 5x6
identity_like_matrix = np.zeros((5, 6))
np.fill_diagonal(identity_like_matrix, 1)

print(identity_like_matrix)


[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]]


import numpy as np
a=np.random.randint(0,10,(3,3))
 b=np.random.randint(10,20,(3,3))
 print(np.add(a,b))
 print(np.subtract(a,b))
 print(np.multiply(a,b))
 print(np.divide(a,b))
 array=[1,3,4,5]
 trans=np.transpose(array)
 print(trans)

 

